sudo: required
dist: trusty

# Do not choose a language; we provide our own build tools.
language: generic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:maarten-fonville/protobuf'
    packages:
      - libgmp-dev
      - gcc-7
      - g++-7
      - cmake-data
      - cmake
      - libopencv-dev
      - libprotobuf-dev
      - protobuf-compiler

matrix:
  include:
    - env: STACK_YAML=stack.yaml
      compiler: ": #GHC 8.4.3"
    - env: STACK_YAML=stack.yaml
      compiler: ": #GHC 8.4.3"
      os: osx
    - env: STACK_YAML=stack-ghc-8.2.yaml
      compiler: ": #GHC 8.2.2"
    - env: STACK_YAML=stack-ghc-8.0.yaml
      compiler: ": #GHC 8.0.2"
    - env: STACK_YAML=stack-ghc-7.10.yaml
      compiler: ": #GHC 7.10.3"
    - env: STACK_YAML=stack-ghc-7.8.yaml
      compiler: ": #GHC 7.8.4"

env:
  global:
    - MKL_DNN_REV: v0.16
    - MKL_DNN_INSTALL_SUFFIX: -0.16
    - MENOH_REV: v1.1.1
    - MENOH_INSTALL_SUFFIX: -1.1.1

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
  - $HOME/mkl-dnn${MKL_DNN_INSTALL_SUFFIX}
  - $HOME/menoh${MENOH_INSTALL_SUFFIX}

before_install:
# Download and unpack the stack executable
- mkdir -p $HOME/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- |
  if [ `uname` = "Darwin" ]; then
    travis_retry curl -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 -C ~/.local/bin '*/stack'
  else
    travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  fi

install:
# Build dependencies
- |
  if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    brew update
    brew upgrade python
    export PATH=/usr/local/opt/python/libexec/bin:$PATH
    brew install mkl-dnn protobuf
  else
    bash .travis/install_mkldnn.sh
  fi
- bash .travis/install_menoh.sh
- export PKG_CONFIG_PATH=$HOME/menoh${MENOH_INSTALL_SUFFIX}/share/pkgconfig:$PKG_CONFIG_PATH
- export LD_LIBRARY_PATH=$HOME/menoh${MENOH_INSTALL_SUFFIX}/lib:$HOME/mkl-dnn${MKL_DNN_INSTALL_SUFFIX}/lib:$LD_LIBRARY_PATH
- stack --jobs 2 --no-terminal --install-ghc build --test --bench --only-dependencies $FLAGS

script:
# Build the package, its tests, and its docs and run the tests
- stack --jobs 2 --no-terminal test --bench --no-run-benchmarks $FLAGS
- stack exec mnist_example
